Add Discard class
purescript/purescript-prelude pull request #115
Opened 2017-02-11 20:56 UTC by paf31

To support https://github.com/purescript/purescript/issues/1803

I tried a few different approaches, and this one seems nicest. It has the additional benefit that you can now use `do` notation with an arbitrary `Apply`, as long as you discard the results.

2017-02-11 20:58 UTC, paf31 commented on src/Control/Bind.purs
> +  discard u f = u *> f unit
Maybe this needs to use `>>=` actually, if we don't want it to always strictly evaluate `f`.

2017-02-11 23:32 UTC, garyb commented on src/Control/Bind.purs
> +  discard u f = u *> f unit
Good point!

2017-02-11 23:53 UTC, rightfold commented
Void instance?

2017-02-12 00:12 UTC, paf31 commented
Hmm, I'm not sure about `Void`.

2017-02-12 18:42 UTC, garyb approved these changes

2017-02-12 18:43 UTC, garyb requested changes
Actually, looks like there's an unused `unit` import :smile:

2017-02-12 20:58 UTC, paf31 commented
Fixed, thanks.

2017-02-12 21:20 UTC, garyb approved these changes

2017-02-13 17:37 UTC, merged

2017-02-13 17:38 UTC, paf31 commented
Do we want to merge some other PRs before making a release?

2017-02-13 18:19 UTC, hdgarrood commented
I think #112 and #114 would be good to merge before making a release. #112 is just a docs update, and #114 is a bug fix. #111 is still a way from being mergeable though.