Implement Data.Reflectable
purescript/purescript-prelude pull request #289
Opened 2022-03-16 14:28 UTC by PureFunctor

Closes #286. Adds a `Data.Reflectable` module which is where the compiler looks at for the automatically-solved `Reflectable` type class.

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

2022-03-16 14:37 UTC, JordanMartinez requested changes
Could you add tests for both the Reflectable and Reifiable type classes?

2022-03-16 14:47 UTC, PureFunctor commented
Should I copy-paste the tests from the compiler? https://github.com/purescript/purescript/blob/1d5c618054bc0c452128e8758dc01b758a3a6f39/tests/purs/passing/SolvingReflectable.purs

2022-03-16 15:21 UTC, thomashoneyman commented on src/Data/Reflectable.purs
> +-- | ```hs
```suggestion
-- | ```purs
```

2022-03-16 15:52 UTC, JordanMartinez commented
> Should I copy-paste the tests from the compiler? https://github.com/purescript/purescript/blob/1d5c618054bc0c452128e8758dc01b758a3a6f39/tests/purs/passing/SolvingReflectable.purs
> 
> I think testing `Reflectable` here would be a bit redundant given the compiler tests. Similarly, tests for `IsSymbol` is done there too. I'm fine with either way, though :sweat_smile:

I think adding it here forces other backends to also implement the tests, which aren't being tested in the compiler. We'd also probably want something more granular.
```purs
testReflection :: AlmostEff
testReflection = do
  assert "Symbol reflection" $ reflectType (Proxy :: Proxy "foo") == "foo"
  assert "Int reflection - 1" $ reflectType (Proxy :: Proxy 1) == 1
  assert "Int reflection - 0" $ reflectType (Proxy :: Proxy 0) == 0
  assert "Int reflection - (-1)" $ reflectType (Proxy :: Proxy (-1)) == (-1)
  assert "Boolean - True reflection" $ reflectType (Proxy :: Proxy PB.True) == true
  assert "Boolean - False reflection" $ reflectType (Proxy :: Proxy PB.False) == false
  assert "Ordering - LT reflection" $ reflectType (Proxy :: Proxy PO.LT) == LT
  assert "Ordering - EQ reflection" $ reflectType (Proxy :: Proxy PO.EQ) == EQ
  assert "Ordering - GT reflection" $ reflectType (Proxy :: Proxy PO.GT) == GT
```
Similarly for the `Reifiable` which isn't being tested by anything, right?

2022-03-17 02:11 UTC, JordanMartinez approved these changes

2022-03-17 02:11 UTC, JordanMartinez commented
:ping_pong: @thomashoneyman

2022-03-17 03:04 UTC, thomashoneyman approved these changes
👍 thanks, @PureFunctor!

2022-03-17 03:04 UTC, merged